---
# This file contains search specifications used by the website module; for details
# on the workings of this file, see the comments in searchspecs.yaml.
#-----------------------------------------------------------------------------------

AllFields:
  DismaxFields:
    - title^750
    - description^300
    - keywords^200
    - url_keywords^50
    - fulltext
  QueryFields:
    title:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10]
    description:
      - [onephrase, 350]
      - [and, 300]
      - [or, ~]
    keywords:
      - [onephrase, 250]
      - [and, 200]
      - [or, ~]
    url_keywords:
      - [onephrase, 100]
      - [and, 50]
      - [or, ~]
    fulltext:
      - [onephrase, 25]
      - [and, 5]
      - [or, ~]
